name: End-to-end tests

on:
  push:
  
jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress test
          npx cypress run --spec "cypress\e2e\1-getting-started\todo.cy.js"  

    
