name: End-to-end tests

on:
  push:
  
jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installer les dépendances npm, les mettre en cache correctement
      # et exécuter un seul test Cypress spécifique

      - name: Install Dependencies and Run Cypress test
        run: |
          npm install
          run --spec "cypress\e2e\1-getting-started\todo.cy.js"
